//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyOrder
    {
        public long OrderID { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<long> CartID { get; set; }
    
        public virtual Cart Cart { get; set; }
    }
}
